-- Day 35: SEQUENCE, SERIAL, IDENTITY
-- PostgreSQL practice file

-- =========================================================
-- 1. BASIC IDENTITY: GENERATED ALWAYS
-- =========================================================

CREATE TEMP TABLE employee_demo (
    id INTEGER GENERATED ALWAYS AS IDENTITY,
    employee_name TEXT NOT NULL
);

INSERT INTO employee_demo (employee_name)
VALUES
    ('Anna'),
    ('Boris'),
    ('Maria');

SELECT *
FROM employee_demo
ORDER BY id;


-- =========================================================
-- 2. GENERATED ALWAYS AND OVERRIDING SYSTEM VALUE
-- =========================================================

-- Direct manual insertion into GENERATED ALWAYS is not allowed:
-- INSERT INTO employee_demo (id, employee_name)
-- VALUES (10, 'Alex');

-- Explicit value is allowed with OVERRIDING SYSTEM VALUE:

INSERT INTO employee_demo (id, employee_name)
OVERRIDING SYSTEM VALUE
VALUES (10, 'Alex');

-- Manual insertion does not move the identity sequence.

INSERT INTO employee_demo (employee_name)
VALUES ('Olga');

SELECT *
FROM employee_demo
ORDER BY id;


-- =========================================================
-- 3. pg_get_serial_sequence() AND setval()
-- =========================================================

SELECT pg_get_serial_sequence('employee_demo', 'id');

-- Set current sequence value to 10.
-- true means that 10 is considered already used.
-- The next generated value will be 11.

SELECT setval(
    pg_get_serial_sequence('employee_demo', 'id'),
    10,
    true
);

INSERT INTO employee_demo (employee_name)
VALUES ('Ivan');

SELECT *
FROM employee_demo
ORDER BY id;


-- =========================================================
-- 4. GENERATED BY DEFAULT AS IDENTITY
-- =========================================================

CREATE TEMP TABLE project_demo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    project_name TEXT NOT NULL
);

INSERT INTO project_demo (project_name)
VALUES
    ('Alpha'),
    ('Beta');

-- BY DEFAULT allows explicit user values.

INSERT INTO project_demo (id, project_name)
VALUES (10, 'Gamma');

-- Manual insertion does not move the identity sequence.

INSERT INTO project_demo (project_name)
VALUES ('Delta');

SELECT *
FROM project_demo
ORDER BY id;


-- =========================================================
-- 5. RESTART WITH
-- =========================================================

ALTER TABLE project_demo
ALTER COLUMN id
RESTART WITH 11;

-- RESTART WITH 11 means that the next generated value is 11.

INSERT INTO project_demo (project_name)
VALUES ('Epsilon');

SELECT *
FROM project_demo
ORDER BY id;


-- =========================================================
-- 6. setval(): true vs false
-- =========================================================

CREATE TEMP TABLE invoice_demo (
    id INTEGER GENERATED ALWAYS AS IDENTITY,
    invoice_number TEXT NOT NULL
);

INSERT INTO invoice_demo (invoice_number)
VALUES
    ('INV-001'),
    ('INV-002'),
    ('INV-003');

-- true:
-- 100 is considered already used.
-- Next generated value = 101.

SELECT setval(
    pg_get_serial_sequence('invoice_demo', 'id'),
    100,
    true
);

INSERT INTO invoice_demo (invoice_number)
VALUES ('INV-004');

SELECT *
FROM invoice_demo
ORDER BY id;


-- =========================================================
-- 7. ROLLBACK DOES NOT ROLLBACK SEQUENCE VALUES
-- =========================================================

CREATE TEMP TABLE rollback_demo (
    id INTEGER GENERATED ALWAYS AS IDENTITY,
    name TEXT NOT NULL
);

INSERT INTO rollback_demo (name)
VALUES ('First');

BEGIN;

INSERT INTO rollback_demo (name)
VALUES ('Second');

ROLLBACK;

-- The row with id = 2 is rolled back,
-- but the sequence value is not rolled back.

INSERT INTO rollback_demo (name)
VALUES ('Third');

SELECT *
FROM rollback_demo
ORDER BY id;


-- =========================================================
-- 8. SERIAL EXAMPLE
-- =========================================================

CREATE TEMP TABLE serial_demo (
    id SERIAL,
    item_name TEXT NOT NULL
);

INSERT INTO serial_demo (item_name)
VALUES
    ('Item A'),
    ('Item B');

SELECT *
FROM serial_demo
ORDER BY id;

-- SERIAL is PostgreSQL-specific shorthand.
-- It creates:
-- INTEGER column
-- sequence
-- DEFAULT nextval(...)
-- sequence ownership linkage


-- =========================================================
-- 9. IMPORTANT NOTES
-- =========================================================

-- INTEGER alone does not generate values automatically.

-- GENERATED BY DEFAULT AS IDENTITY:
-- user can explicitly insert an id.

-- GENERATED ALWAYS AS IDENTITY:
-- direct explicit insertion is rejected.
-- OVERRIDING SYSTEM VALUE allows explicit insertion.

-- Manual insertion of a large id does not automatically
-- synchronize the identity sequence.

-- RESTART WITH N:
-- N becomes the next generated value.

-- setval(sequence, N, true):
-- N is considered already used.
-- next generated value will be N + 1.

-- setval(sequence, N, false):
-- N is not considered used yet.
-- next generated value will be N.

-- Sequence values are not transactional.
-- ROLLBACK does not return consumed sequence values.

-- Gaps in auto-generated ids are normal.
